name: Set up environment
description: Set up an anaconda-linter environment

env:
  # The version of Python to use by all steps.
  PYTHON_VERSION: "3.11"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'
    - name: Cache conda env
      id: cache-conda
      uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
      env:
        cache-name: conda-env-cache
      with:
        cache: 'pip'
        path: '/usr/share/miniconda/envs'
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/environment.yml') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Create Environment
      shell: bash
      if: ${{ steps.cache-conda.outputs.cache-hit == false }}
      run: |
        conda update -n base -c defaults conda
        source $CONDA/etc/profile.d/conda.sh
        conda init bash
        conda create --name anaconda-linter -y python=${{ env.PYTHON_VERSION }}
        conda install --name anaconda-linter -c distro-tooling -y anaconda-linter
        source $CONDA/bin/activate
        conda activate anaconda-linter
        conda-lint --fix feedstock/
